stages:
  - test
  - publish

test-3.8:
  stage: test
  image: python:3.8
  script:
    - pip install 'poetry<2' nox
    - nox -p 3.8 -s lint mypy pytype tests
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "master"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test-3.9:
  stage: test
  image: python:3.9
  script:
    - pip install 'poetry<2' nox
    - nox --sessions tests-3.9
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "master"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

publish-test-pypi:
  stage: publish
  image: python:3.8
  script:
    - pip install 'pip<24' 'poetry<2'
    - >-
      poetry version patch &&
      version=$(poetry version | awk '{print $2}') &&
      poetry version $version.dev.$(date +%s)
    - poetry build
    - poetry publish --username=__token__ --password=$PYPI_TOKEN --repository testpypi
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

publish-pypi:
  stage: publish
  image: python:3.8
  script:
    - pip install 'pip<24' 'poetry<2' nox
    - nox -p 3.8
    - poetry build
    - poetry publish --username=__token__ --password=$PYPI_TOKEN
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v/'
